### ISSUE TITLE
export data from rfid to .csv

### ISSUE THREAD

**Issue by Tusker13-04** [Tusker13-04/smart-attendance-system#1]
let's work out a way to export the data collected to .csv

**Comment by TheLengendaryWiz** [comment]
We'll have to check in what format the data rfid comes. I suggest you first try out the rfid reader and see in what format the data from rfid comes

**Comment by TheLengendaryWiz** [comment]
We will be using json not CSV. That is the reason I closed this issue , in case there is a lack of clarity on why I did so.
